config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admins
  default_url_options :host => "https://www.wehirefitness.com"

  root 'home#index'

  # jobs
  get '/jobs/new', to: 'jobs#new'

  post '/jobs/review', to: 'jobs#review'
  get '/jobs/review', to: 'jobs#review'

  post '/jobs/purchase', to: 'jobs#purchase'
  get '/jobs/purchase', to: 'jobs#purchase'

  post '/jobs/complete_purchase', to: 'jobs#complete_purchase'

  get '/jobs/thank_you', to: 'jobs#thank_you'

  get '/jobs/:id', to: 'jobs#show', as: 'job'

  post '/jobs/charge_and_publish', to: 'jobs#charge_and_publish'
  post '/jobs/unpublish', to: 'jobs#unpublish'
  post '/jobs/publish', to: 'jobs#publish'


  # seekers
  post '/seeker/create', to: 'seeker#create'

  # coupons
  get '/coupons/lookup/:code', to: 'coupons#lookup'

  #misc
  get '/terms', to: 'legal#terms_and_conditions'
  get '/privacy', to: 'legal#privacy_policy'

  get '/sitemap.:format', to: 'home#sitemap'
end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title,
						:category,
						:description,
						:how_to_apply,
						:company_description,
						:company_name,
						:company_url,
						:company_email,
						:zip,
						:city,
						:state,
						presence: true

	validates_uniqueness_of :origin_uid, allow_nil: true, allow_blank: true
	geocoded_by 			:full_address
	before_save       :geocode
	after_validation 	:set_full_address, on: [:create, :update]
	belongs_to :coupon

	def get_full_address
    [city, state, zip.to_s].reject(&:blank?).join(' ')
  end

  scope :visible, -> { where('published=? AND created_at > ?', true, 30.days.ago) }
  scope :unpublished, -> { where('published=? AND created_at > ?', false, 30.days.ago) }

	def charge_and_publish
		amount = 2500
		if self.coupon && self.coupon.can_use?
			amount = amount - (amount * self.coupon.as_float).round
			self.coupon.use
		end

		if amount > 0
			begin
				charge = Stripe::Charge.create(
			    :customer    => self.stripe_customer_id,
			    :amount      => amount,
			    :description => 'wehirefitness.com Job Posting',
			    :currency    => 'usd'
			  )
			rescue Stripe::CardError => e
			  return {success: false, message: e.message}
			end

			self.stripe_charge_id = charge.id
		end

		self.published = true
		self.save

		JobMailer.new_job_receipt(self, charge).deliver_now

		return {success: true, amount_charged: amount}
	end

  private

  def set_full_address
    self.full_address = get_full_address
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	include ActionView::Helpers::AssetUrlHelper

	def show
		if current_admin
			@job = Job.find_by_id(params[:id])
		else
			@job = Job.visible.find_by_id(params[:id])
		end

    if @job
      set_meta_tags :title => @job.title + " at " + @job.company_name
			description = @job.description.split[0...40].join(' ')
			icon_url = asset_url("assets/twitter/misc.png")

			set_meta_tags	description: description,
										twitter: {
											description: description,
											image: icon_url
										},
										og: { description: description}
    else
      set_meta_tags :title => "Job not found"
    end
	end

	def new
		@job = Job.new(session[:job])
    set_meta_tags :title => "Describe your job listing"
	end

	def review
		if(params[:job] || session[:job])
      set_meta_tags :title => "Review your job listing"

			if(params[:job])
				session[:job] = job_params
			end

			@job = Job.new(session[:job])
			@category = Category.find_by_id(@job.category)
		else
			redirect_to jobs_new_path
		end
	end

	def purchase
    set_meta_tags :title => "Almost there..."
	end

	def publish
		if !current_admin
			redirect_to root_path
		end

		@job = Job.find_by_id(params[:id])
		@job.published = true
		@job.save

		redirect_to action: "show", id: @job.id
	end

	def unpublish
		if !current_admin
			redirect_to root_path
		end

		@job = Job.find_by_id(params[:id])
		@job.published = false
		@job.save

		redirect_to action: "show", id: @job.id
	end

	def charge_and_publish
		if !current_admin
			redirect_to root_path
		end

		@job = Job.find_by_id(params[:id])
		response = @job.charge_and_publish

		if !response[:success]
			flash[:error] = response[:message]
		  return redirect_to action: "show", id: @job.id
		end

		redirect_to action: "show", id: @job.id
	end

	def complete_purchase
		@job = Job.new(session[:job])

		if current_admin
			@job = Job.new(session[:job])
			@job.stripe_charge_id = 'admin_job_posting'
			@job.published = true
			if @job.save
				session[:job] = nil
				flash[:notice] = 'Admin - job has been publisehd'
				return redirect_to jobs_thank_you_path
			end
			flash[:error] = @job.errors.full_messages
			return redirect_to jobs_purchase_path
		end

		if !@job.valid?
			flash[:error] = @job.errors.full_messages
			return redirect_to jobs_purchase_path
		end

		begin
		  customer = Stripe::Customer.create(
		    :email => session[:job][:company_email],
		    :card  => params[:stripeToken]
		  )
			@job.stripe_customer_id = customer.id
		rescue Stripe::CardError => e
		  flash[:error] = e.message
		  return redirect_to jobs_purchase_path
		end

		if coupon_code = params[:coupon_code]
			coupon = Coupon.find_by_code(coupon_code)
			@job.coupon = coupon if coupon.present? && coupon.can_use?
		end

		if @job.save
			session[:job] = nil
			flash[:notice] = 'Your job has been created!'
	    SlackModule::API::notify_new_job_posting(job_url(@job), @job.title)
			JobMailer.new_job(@job).deliver_now
			JobMailer.new_job_admin_notification(@job).deliver_now
			return redirect_to jobs_thank_you_path
		end
		flash[:error] = @job.errors.full_messages
		return redirect_to jobs_purchase_path
	end

	def thank_you
    set_meta_tags :title => "Your job has been posted!"
	end

  private

  def job_params
    params.require(:job).permit(:title, :category, :city, :state, :zip, :description, :how_to_apply, :company_description, :company_name, :company_url, :company_email )
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job.html.erb
<div class='job-posting'>
  <div class='job-header'>
    <h2 class='job-title'><%= job.title %></h2>
    <h6 class='posted-on'>Posted <%= (job.created_at || Date.today).strftime('%b %d') %></h6>
    <p class='company-details'>
      <span class='company'><%= link_to job.company_name, job.company_url, target: '_blank' %></span>
      <br />
      <span class='location'><%= job.city %>, <%= @job.state %></span>
    </p>
  </div>

  <section class='job-description'>
    <h4>About this position</h4>
    <%=raw job.description %>
  </section>

  <div class='apply-wrap'>
    <h4>How to apply for this job</h4>
    <br>
    <%=raw job.how_to_apply %> Be sure to mention you found this job on WeHireFitness.com.
  </div>

  <div class='apply-wrap'>
    <h4>What <%= job.company_name %> is about</h4>
    <br>
    <%=raw job.company_description %>
  </div>
</div>

app/views/jobs/new.html.erb
<%= link_to 'Home', root_path, :class => 'button back' %>
<br />
<br />
<%= form_for(@job, :url => { :action => :review }) do |f| %>
  <h1>Let's get started</h1>
  <p>Your job listing will remain on this site for 30 days. After 30 days your job listing will expire and be removed. You can always post the job again by filling out this form and making the $25 payment for an additional 30 days.</p>

  <hr />
  <h3>About the job...</h3>
  <div class="field">
    <%= f.label :job_title %>
    <div class='description'>"Yoga Teacher" or “Zumba Instructor”</div>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, options_for_select(category_selects, @job.category), :name=>'category', :id=>'category' %>
  </div>

   <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.select :state, options_for_select(us_states, @job.state), :name=>'state', :id=>'state' %>
  </div>

   <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <div class='description'>Detailed information about this job posting.</div>

    <%= f.bootsy_area :description, id: 'description_editor', 'placeholder' => :description %>
  </div>

  <div class="field">
    <%= f.label :how_to_apply %><br>
    <div class='description'>Example: Send your resume to hr@mybusiness.com</div>
    <%= f.bootsy_area :how_to_apply, id: 'apply_editor' %>
  </div>

  <hr />
  <h3>About your company...</h3>
  <div class="field">
    <%= f.label :name %><br>
    <div class='description'>Enter your company name.</div>
    <%= f.text_field :company_name, id: 'about_editor' %>
  </div>

  <div class="field">
    <%= f.label :About %><br>
    <div class='description'>A short description of your company.</div>
    <%= f.bootsy_area :company_description, id: 'company_editor' %>
  </div>

  <div class="field">
    <%= f.label :Website %><br>
    <div class='description'>Example: https://mybusiness.com/careers/</div>
    <%= f.text_field :company_url %>
  </div>

  <div class="field">
    <%= f.label :Email %><br>
    <div class='description'>This is where we’ll send the receipt, confirmation, and all activity on your job listings.</div>
    <%= f.text_field :company_email %>
  </div>

  <div class="actions">
    <%= f.submit 'Preview your job posting', :class => 'forward' %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function () {
    $('#new_job').validate({
      debug: true,
      rules: {
        'job[title]': { required: true },
        'job[city]': { required: true },
        'job[zip]': { required: true },
        'job[description]': { required: true },
        'job[how_to_apply]': { required: true },
        'job[company_name]': { required: true },
        'job[company_description]': { required: true },
        'job[company_url]': { required: true },
        'job[company_email]': { required: true, email: true },
      },
      submitHandler: function(form) {
        form.submit();
      }
    });
  });
</script>

app/views/jobs/purchase.html.erb
<%= link_to 'Back to review', jobs_review_path, :class => 'button back' %>
<br />
<br />
<br />


<%= form_tag("/jobs/complete_purchase",
  url: "/jobs/complete_purchase",
  id: 'payment-form',
  role: 'form',
  authenticity_token: true) do %>

  <h1>Almost there...</h1>
  <p>
    Your ad is $25 and it will run for 30 days starting today.

    Your ad will be reviewed by our staff before being listed on the main page. This only takes a few minutes. We reserve the right to deny or remove ads at our discretion (we will refund your money if we don’t run your ad). Any questions? Contact us by emailing support@wehirefitness.com
  </p>

  <br>

  <%= label_tag :coupon_code, 'Apply a coupon' %><br><br>
  <span id='coupon-message' class='color-red'></span><br>
  <%= text_field_tag :coupon_field, '', placeholder: 'Coupon code' %>
  <button type="submit" class='button js-apply-coupon'>Apply coupon</button>

  <br>
  <table class='table table-condensed'>
    <thead>
      <tr><th colspan="2"><h5>Checkout</h5></th></tr>
    </thead>
    <tbody>
      <tr>
        <td>Wehirefitness.com Job Posting</td>
        <td>$25.00</td>
      </tr>
      <tr>
        <td>Discount<span class='js-discount-name'></span></td>
        <td>$<span class='js-discount-amount'>0.00</span></td>
      </tr>
      <tr>
        <td><strong>Total</strong></td>
        <td><strong>$<span class='js-total-amount'>25.00</span></strong></td>
      </tr>
    </tbody>
  </table>

  <br>
  <div class='payment-errors'></div>

  <%= render '/billing/card' %>

  <br />

  <script type="text/javascript">CreditCard.init();</script>

  <button type="submit" class='button forward'>Checkout!</button>
<% end %>

app/views/jobs/review.html.erb
<h1>How does this look?</h1>

<%= link_to 'Make a change', jobs_new_path, :class => 'button back' %>
<br>
<br>
<%= render partial: 'jobs/job', locals: { job: @job } %>

<div class='review-action-wrap'>
	<h6>Almost done – review your listing before posting live</h6>
	<br />
	<%= link_to 'Make a change', jobs_new_path, :class => 'button back' %>

	<% if current_admin %>
		<%= link_to 'Admin - Publish', '/jobs/complete_purchase', :class => 'button forward', :method => :post %>
	<% else %>
		<%= link_to 'Purchase Listing', jobs_purchase_path, :class => 'button forward' %>
	<% end %>
</div>

app/views/jobs/show.html.erb
<%= link_to 'Go back', root_path, class: 'button back' %>
<br>
<br>

<% if @job %>
  <% if current_admin %>
    <% if !@job.published && !@job.stripe_charge_id %>
      <%= link_to 'Publish & charge', jobs_charge_and_publish_path(id: @job.id), :class => 'button', :method => :post %>
    <% end %>

    <% if @job.published %>
      <%= link_to 'Unpublish', jobs_unpublish_path(id: @job.id), :class => 'button', :method => :post %>
    <% elsif @job.stripe_charge_id %>
      <%= link_to 'Republish', jobs_publish_path(id: @job.id), :class => 'button', :method => :post %>
    <% end %>

    <p>Something smell fishy? <%= mail_to @job.company_email, @job.company_email, subject: "", body: '' %></p>
    <br><br><br><br>
  <% end %>

  <%= render partial: 'jobs/job', locals: { job: @job } %>

	<br />
	<br />
	<br ?>
	<p>Something smell fishy? <%= mail_to "info@theyogaclasses.com", "Report this job listing", subject: "Reporting job \##{@job.id}", body: '' %></p>
<% else %>
	<div class='job-header'>
		<h2>Job not found</h2>
		<p>The job listing you were looking for doesn’t seem to exist anymore. Job listings expire in 30 days. It’s possible that the job listing has expired, or it has already been filled.</p>
	</div>
<% end %>

app/views/jobs/thank_you.html.erb
<p>Thank you for being a supporter of WeHireFitness.com.  We are very proud of building a website that helps fitness enthusiast find their dream job AND fitness & Gym companies find those who are most passionate about all things fitness and health.</p>
<br>
<%= link_to 'Head Home', root_path, class: 'button back' %>