config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admins
  default_url_options :host => "https://www.wehirefitness.com"

  root 'home#index'

  # jobs
  get '/jobs/new', to: 'jobs#new'

  post '/jobs/review', to: 'jobs#review'
  get '/jobs/review', to: 'jobs#review'

  post '/jobs/purchase', to: 'jobs#purchase'
  get '/jobs/purchase', to: 'jobs#purchase'

  post '/jobs/complete_purchase', to: 'jobs#complete_purchase'

  get '/jobs/thank_you', to: 'jobs#thank_you'

  get '/jobs/:id', to: 'jobs#show', as: 'job'

  post '/jobs/charge_and_publish', to: 'jobs#charge_and_publish'
  post '/jobs/unpublish', to: 'jobs#unpublish'
  post '/jobs/publish', to: 'jobs#publish'


  # seekers
  post '/seeker/create', to: 'seeker#create'

  # coupons
  get '/coupons/lookup/:code', to: 'coupons#lookup'

  #misc
  get '/terms', to: 'legal#terms_and_conditions'
  get '/privacy', to: 'legal#privacy_policy'

  get '/sitemap.:format', to: 'home#sitemap'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@jobs = {}
		Category.all.each  do |c|
			@jobs[c.name] = Job.where(category: c.id.to_s).visible.reorder('id DESC')
		end

		if current_admin
			@unpublished_jobs = Job.unpublished
		end
	end

  def sitemap
    @jobs = Job.all.visible
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class='pop-box'>
  Here at We Hire Fitness, our mission is to connect employers in the fitness industry with people who are passionate about health, happiness and fitness.
</div>

<p><h4 class='color-blue'>Employers:</h4> You can post job openings from across the country and seek out the best talent.</p>

<p><h4 class='color-blue'>Job seekers:</h4> Will have access to connect with employers and submit your resume directly to hiring managers.  Enough chasing around searching high and low for companies looking for your talent.</p>

<br />
<%= link_to 'Post a job - $25 for 30 days', jobs_new_path, :class => 'button' %>

<% if current_admin && @unpublished_jobs %>
	<div class='jobs-wrap'>
		<div class='category-wrap'>
			<h3 class='title'>Unpublished</h3>
			<% @unpublished_jobs.each do |job| %>
				<div class='job'>
					<span class='company-name'><%= job.company_name %></span>
					<span class='job-title'><%= link_to job.title, job %></span>
					<span class='location'>- <%= job.city %>, <%= job.state %></span>
					<span class='posted-on'><%= job.created_at.strftime('%b %d') %></span>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

<div class='jobs-wrap'>
	<% @jobs.each do | cat_name, jobs | %>
		<div class='category-wrap'>
			<h3 class='title'><%= cat_name %></h3>
			<% if !jobs.present? %>
				<h5 class='no-jobs-found'>No jobs posted</h5>
			<% else %>
				<% jobs.each do |job| %>
					<div class='job'>
            <span class='job-title'><%= link_to job.title, job %></span>
						<span class='company-name'> - <%= job.company_name %></span>
						<span class='location'>- <%= job.city %>, <%= job.state %></span>
						<span class='posted-on'><%= job.created_at.strftime('%b %d') %></span>
					</div>
				<% end %>
			<% end %>
		</div>
	<% end %>
</div>

<div class='page-footer'>Have an idea or would like a new feature for the site?  Send us an <%= mail_to "support@wehirefitness.com", "email", subject: "WeHireFitness.com suggestion", body: '' %> and we’ll do our best to address your request to make sure our customers have the best user experience on YOUR site.</div>