config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admins
  default_url_options :host => "https://www.wehirefitness.com"

  root 'home#index'

  # jobs
  get '/jobs/new', to: 'jobs#new'

  post '/jobs/review', to: 'jobs#review'
  get '/jobs/review', to: 'jobs#review'

  post '/jobs/purchase', to: 'jobs#purchase'
  get '/jobs/purchase', to: 'jobs#purchase'

  post '/jobs/complete_purchase', to: 'jobs#complete_purchase'

  get '/jobs/thank_you', to: 'jobs#thank_you'

  get '/jobs/:id', to: 'jobs#show', as: 'job'

  post '/jobs/charge_and_publish', to: 'jobs#charge_and_publish'
  post '/jobs/unpublish', to: 'jobs#unpublish'
  post '/jobs/publish', to: 'jobs#publish'


  # seekers
  post '/seeker/create', to: 'seeker#create'

  # coupons
  get '/coupons/lookup/:code', to: 'coupons#lookup'

  #misc
  get '/terms', to: 'legal#terms_and_conditions'
  get '/privacy', to: 'legal#privacy_policy'

  get '/sitemap.:format', to: 'home#sitemap'
end

app/views/layouts/_footer.html.erb
<div class='site-footer'>
	<div class='copy-right'>&copy; 2015 The Yoga Classes, llc - All rights reserved</div>
	<div class='legal'>
		<a href='/privacy/'>Privacy Policy</a>
		<span class='divider'> | </span>
		<a href='/terms/'>Terms & Conditions</a>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags :separator => "|".html_safe, reverse: true %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-71611775-1', 'auto');
    ga('send', 'pageview');
  </script>
  <script type='text/javascript' src='https://js.stripe.com/v2/'></script>
  <link href='https://fonts.googleapis.com/css?family=Anton|Raleway' rel='stylesheet' type='text/css'>
</head>
<body class="<%= "#{controller.controller_name} #{@body_class}".strip %>">
  <div id='site-wrap'>
		<header id='site-header'>
      <div class='blue-bar'></div>
      <div class='header-content'>
        <div class='header-img' title='We Hire Fitness'></div>
        <h1><a href='<%= root_path %>'><span class='we'>We</span> <span class='hire'>Hire</span> <span class='fitness'>Fitness</span></a></h1>
      </div>
		</header>

		<% if current_admin %>
			<%= link_to 'Sign Out', destroy_admin_session_path, :method => :delete %>
		<% end %>

		<div id='site-content'>
			<h4 class='notice'><%= flash[:notice] %></h4>

			<%= yield %>

      <%= render partial: 'common/seeker_signup' %>
		</div>

		<footer id='site-footer'>
			<%= render 'layouts/footer' %>
		</footer>
	</div>
</body>
</html>